# Generated by Django 5.0.1 on 2025-06-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('application_number', models.CharField(max_length=20)),
                ('registration_date', models.DateField()),
                ('registration_time', models.TimeField()),
                ('school', models.CharField(max_length=150)),
                ('source', models.CharField(max_length=50)),
            ],
        ),
    ]
