# Generated by Django 5.0.1 on 2025-07-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alma_statistics', '0002_alter_applicant_application_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
