# Generated by Django 5.0.1 on 2025-07-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alma_statistics', '0004_quizquestion_quizanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
